/**
 * Bundles docs/product-docs/** into a single generated TS module the Help
 * Agent imports as a plain string constant. Deliberately NOT read from disk
 * at request time — Vercel's serverless file tracing can't reliably see a
 * directory listing (readdirSync over docs/product-docs/features/*) that's
 * only resolved at runtime, and this codebase already avoids that class of
 * bug elsewhere (see customizationRequests.ts's hand-maintained
 * ARCHITECTURE_CONTEXT, which exists for the same reason). Since these
 * feature docs are auto-generated by /product rather than hand-written,
 * this script just automates producing the equivalent static bundle.
 *
 * Re-run this whenever product docs change: npx tsx scripts/generate-help-docs.ts
 */
import fs from "node:fs";
import path from "node:path";

const DOCS_ROOT = path.join(process.cwd(), "docs", "product-docs");
const OUT_PATH = path.join(process.cwd(), "src", "server", "helpDocsContent.generated.ts");

function walk(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(full));
    else if (entry.name.endsWith(".md")) files.push(full);
  }
  return files;
}

function main() {
  const files = walk(DOCS_ROOT).sort();
  const sections = files.map((f) => {
    const relPath = path.relative(DOCS_ROOT, f).replace(/\\/g, "/");
    const content = fs.readFileSync(f, "utf-8").trim();
    return `<!-- SOURCE: docs/product-docs/${relPath} -->\n${content}`;
  });
  const bundle = sections.join("\n\n---\n\n");

  const output = `// AUTO-GENERATED by scripts/generate-help-docs.ts — do not hand-edit.
// Re-run that script after changing anything under docs/product-docs/.
export const HELP_DOCS_CONTENT = ${JSON.stringify(bundle)};
`;
  fs.writeFileSync(OUT_PATH, output);
  console.log(`Wrote ${OUT_PATH} from ${files.length} doc files (${bundle.length} chars).`);
}

main();
